all: legislators.csv districts.csv

legislators.csv:
	curl -kO "http://unitedstates.sunlightfoundation.com/legislators/legislators.csv"

districts.csv:
	curl -kO "http://assets.sunlightfoundation.com/data/districts.csv"